src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import indexView, postImage, postQuestion

urlpatterns = [
    path('', indexView.as_view()),
    path('ajax/upload/image', postImage),
    path('ajax/upload/question', postQuestion),


]

src/visualqa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(('core.urls', 'core'), namespace='core')),

]

src/core/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext as _


class VQAImage(models.Model):
    image = models.ImageField(_("Upload your image"), upload_to="images/", height_field=None, width_field=None, max_length=None)
    timestamp = models.DateTimeField(_(""), auto_now=False, auto_now_add=True)
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("user"), on_delete=models.CASCADE)


class Question(models.Model):
    question = models.CharField(_("Input your question"), max_length=100)
    answer = models.CharField(_("Answer of the question"), max_length=50)

    timestamp = models.DateTimeField(_(""), auto_now=False, auto_now_add=True)
    image = models.ForeignKey(VQAImage, verbose_name=_("image"), on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("question")
        verbose_name_plural = _("questions")

    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse("_detail", kwargs={"pk": self.pk})

src/core/forms.py
from django import forms
from .models import VQAImage, Question

class ImageForm(forms.ModelForm):
    image = forms.ImageField( label='')

    class Meta:
        model = VQAImage
        exclude = ["user", "timestamp"]

src/core/views.py
from django.shortcuts import render
from core.model.main import MyVQAModel
import os
from django.http import JsonResponse
from django.views import View
import numpy as np
import cv2
from .forms import ImageForm
import tensorflow as tf
from .models import Question, VQAImage

# Create your views here.
vqaModel = None
class indexView(View):
    def get(self, *args, **kwargs):
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        imageform = ImageForm()
        return render(self.request, "index.html", {"form": imageform})


def postImage(request):
    if request.method == "POST" and request.is_ajax():
        instance = ImageForm(request.POST, request.FILES)
        instance = instance.save()
        global vqaModel
        vqaModel = get_tfa_model()
        # instance.user = request.user
        return JsonResponse({"success":True, "image_id": instance.id}, status=200)
    return JsonResponse({"success":False}, status=400)


def get_tfa_model(retry = 3):
    vqaModel = None
    if not retry:
        return None

    with tf.Graph().as_default():
        try:
            vqaModel = MyVQAModel()
        except Exception as e:
            print("Retrying!!")
            get_tfa_model(retry-1)

    return vqaModel


def postQuestion(request):
    if request.method == "GET" and request.is_ajax():
        instance = Question()
        question = request.GET.get("question", None)
        image_id = request.GET.get("image_id", None)
        question_no = int(request.GET.get("question_no", None))
        print(question)
        if question and image_id:
            instance.question = question
            instance.image = VQAImage.objects.get(id = image_id)
            try:
                answers = vqaModel.run(instance.image.image.url, question, question_no)
            except Exception as e:
                return JsonResponse({"errors":e}, status=400)
            print(answers)
            instance.answer = answers[0]["label"]
            instance.save()
            return JsonResponse({"answers":answers}, status=200)

    return JsonResponse({"success":False}, status=400)

src/core/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <style>
    body {
        font-family: 'Roboto', sans-serif;
    }
    </style>
    {% block style %}
    {% endblock %}

</head>

<body>
    {% block content %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block script %}
    {% endblock %}
</body>

</html>

src/core/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">

{% endblock %}

{% block content %}


<div class="container">

    <h2>Visual Question Answering</h2>
    <p class="lead"><b>Upload any Image and get your queries answered</b></p>
    <!-- Upload  -->
    <form class="uploader" id="file-upload-form" method="POST" novalidate="" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_image" id="file-drag">
            <img id="file-image" src="#" alt="Preview" class="hidden">
            <div id="start">
                <i class="fa fa-download" aria-hidden="true"></i>
                <div>Select a image file or drag here</div>
                <div id="notimage" class="hidden">Please select an image</div>
                <span id="file-upload-btn" class="btn btn-primary">Select a image file</span>
            </div>
            <div id="response" class="hidden">
                <div id="messages"></div>
                <progress class="progress" id="file-progress" value="0">
                    <span>0</span>%
                </progress>
            </div>
        </label>

        {{form}}

    </form>


    <div id="question_area" class=" center-block" style="margin:0 auto;">
        <form id="questionForm">{% csrf_token %}
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" id="question"
                     placeholder = "Enter your question here"
                     name="question">
                    <input type="hidden" class="form-control" id="image_id" name="image_id">

                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit" id="ask_question"
                            data-loading-text="<span class='glyphicon glyphicon-refresh glyphicon-spin'></span> Processing">
                            Ask!</button>
                    </span>
                </div>
                <p class = "mute">First question result usually takes time</p>
            </div>
        </form>
    </div>
    <div id="answer_area"></div>
</div>


{% endblock %}

{% block script %}
<script src="{% static 'js/index.js' %}"></script>

{% endblock %}